<!DOCTYPE html>
	<head>
	<!--Author: Darrel Scott-->
	<!--Class: CSCIU450-01-SPRING-2018-->
	<!--Purpose: Semester Long Website Project-->
	<!--Company: Tony the Peanut Man-->

	<?php if(empty($title)) $title="Tony The Peanut Man"; ?>
			
			
	<link href="https://fonts.googleapis.com/css?family=Arima+Madurai" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css?family=Cookie" rel="stylesheet"> 
	<link href="https://fonts.googleapis.com/css?family=PT+Sans|Slabo+27px" rel="stylesheet"> 	
	<link rel='stylesheet' type='text/css' href='reset.css'>
	<link rel='stylesheet' type='text/css' href='style.css'>
	<meta name='viewport' content='width=device-width, initial-scale=1.0'>
	<script defer src="https://use.fontawesome.com/releases/v5.0.9/js/all.js" integrity="sha384-8iPTk2s/jMVj81dnzb/iFR2sdA7u06vHJyyLlAd4snFpCl/SnyUjRrbdJsw1pGIl" crossorigin="anonymous"></script>	
    </head>	
	
	<body>
<!--Header--><!--Header--><!--Header--><!--Header--><!--Header--><!--Header--><!--Header--><!--Header--><!--Header--><!--Header--><!--Header-->	
		<div class='header'>		
			
				<img src='images/logo.png'>
			
		</div>


<!--Menu--><!--Menu--><!--Menu--><!--Menu--><!--Menu--><!--Menu--><!--Menu--><!--Menu--><!--Menu--><!--Menu--><!--Menu--><!--Menu--><!--Menu-->

	<div class='menu'>
		<ul>
			<li>	
				<a href='index.html'>Home</a>
			</li>
			<li>	
				<a href='products.html'>Products</a>
			</li>
			<li>	
				<a href='order.html'>Order</a>
			</li>			
			<li>	
				<a href='about.html'>About</a>
			</li>	
			<li>	
				<a href='contact.html'>Contact</a>
			</li>
			<li>
			<a href='login.html'>Login</a>
			</li>
			<li>
			<a href='cart.html'><i class="fas fa-shopping-cart"></i></a>
			</li>
		</ul>
	</div>	

	
<!--Content--><!--Content--><!--Content--><!--Content--><!--Content--><!--Content--><!--Content--><!--Content--><!--Content--><!--Content-->
	<!--Opening Statement-->
	<div id ='content'>